  
baseURL = "http://example.com/"
languageCode = "es"
title = "Escuela Vaciada"
theme = "soho"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true


[params]
    author = "Antonio Matas"
    description = "Sitio web del proyecto Escuela Vaciada"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.png"

copyright = "Author Name"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
  
  


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

 [[params.socialIcons]]
    url = "mailto:amatas@uma.es"
    name = "fas fa-envelope"
    weight = 1

 [[params.socialIcons]]
    url = "https://gitlab.com/amataste"
    name = "fab fa-gitlab"
    weight = 2

 [[params.socialIcons]]
    url = "https://twitter.com/Red_Idei"
    name = "fab fa-twitter"
    weight = 3

 [[params.socialIcons]]
    url = "https://www.linkedin.com/in/antonio-matas-mateoferran"
    name = "fab fa-linkedin"
    weight = 4

 [[params.socialIcons]]
    url = "https://stackoverflow.com/users/19774826/antonio-matas"
    name = "fab fa-stack-overflow"
    weight = 5
