baseURL: https://escuelavaciada.netlify.app/
languageCode: en-us
title: Escuela Vaciada
theme: minimal
# disqusShortname: username
googleAnalytics: ''
params:
  accent: red
  author: Calin Tataru
  backgroundColor: white
  description: Sitio web del proyecto Escuela Vaciada
  font: Raleway
  githubUsername: '#'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fas fa-envelope
      url: mailto:amatas@uma.es
      weight: 1
    - name: fab fa-gitlab
      url: https://gitlab.com/amataste
      weight: 2
    - name: fab fa-twitter
      url: https://twitter.com/Red_Idei
      weight: 3
    - name: fab fa-linkedin
      url: https://www.linkedin.com/in/antonio-matas-mateoferran
      weight: 4
    - name: fab fa-stack-overflow
      url: https://stackoverflow.com/users/19774826/antonio-matas
      weight: 5
  main:
    - name: Inicio
      url: /
      weight: 1
    - name: Al respecto
      url: /about/
      weight: 2
    - name: Publicaciones
      url: /post/
      weight: 3
    - name: Acciones
      url: /project/
      weight: 4
