baseURL: https://escuelavaciada.netlify.app/
languageCode: en-us
title: Escuela Vaciada
theme: hugo-kiera
# disqusShortname: username
googleAnalytics: ''
params:
  accent: red
  author: Calin Tataru
  backgroundColor: white
  description: Sitio web del proyecto Escuela Vaciada
  font: Raleway
  githubUsername: '#'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu: "main"
meta: "false"



